# Project Organization Script
# Run this to automatically organize your Area Recommendation Analysis project

# Set working directory
setwd("c:/Users/User_Pc")

# Create function to safely move files
safe_move <- function(source_pattern, destination_folder, description) {
  files <- list.files(pattern = source_pattern, full.names = TRUE)
  if (length(files) > 0) {
    for (file in files) {
      if (file.exists(file)) {
        file.copy(file, file.path(destination_folder, basename(file)), overwrite = TRUE)
        file.remove(file)
        cat("✅ Moved", basename(file), "to", destination_folder, "\n")
      }
    }
    cat("📁", description, "- Moved", length(files), "files\n")
  } else {
    cat("ℹ️ No files found matching pattern:", source_pattern, "\n")
  }
}

# Move files to appropriate folders
cat("🗂️ Organizing Area Recommendation Analysis Project...\n\n")

# 1. Move any remaining CSV files to OBTAINED DATA (except processed ones)
raw_csv_files <- list.files(pattern = "\\.csv$", full.names = TRUE)
processed_files <- c("area_recommendations.csv", "top_10_recommendations.csv", 
                     "top_3_recommendations.csv", "data_coverage_summary.csv",
                     "modeling_dataset.csv")

for (csv_file in raw_csv_files) {
  filename <- basename(csv_file)
  if (!filename %in% processed_files) {
    if (file.exists(csv_file)) {
      file.copy(csv_file, file.path("OBTAINED DATA", filename), overwrite = TRUE)
      file.remove(csv_file)
      cat("✅ Moved", filename, "to OBTAINED DATA\n")
    }
  }
}

# 2. Move processed/cleaned data files to CLEANED DATA
processed_patterns <- c("*_summary\\.csv$", "*recommendations*\\.csv$", "*modeling*\\.csv$", 
                       "*coverage*\\.csv$", "*final*\\.csv$", "*combined*\\.csv$")

for (pattern in processed_patterns) {
  safe_move(pattern, "CLEANED DATA", "Processed data files")
}

# 3. Move visualization files to GRAPHS
safe_move("\\.png$", "GRAPHS", "Visualization files (PNG)")
safe_move("\\.pdf$", "GRAPHS", "Visualization files (PDF)")

# 4. Move recommendation system outputs to RECOMMENDATION SYSTEM
rec_patterns <- c("*recommendation*", "*score*", "*ranking*")
for (pattern in rec_patterns) {
  files <- list.files(pattern = paste0(pattern, "\\.(csv|txt|md)$"), full.names = TRUE)
  if (length(files) > 0) {
    for (file in files) {
      if (file.exists(file)) {
        file.copy(file, file.path("RECOMMENDATION SYSTEM", basename(file)), overwrite = TRUE)
        file.remove(file)
        cat("✅ Moved", basename(file), "to RECOMMENDATION SYSTEM\n")
      }
    }
  }
}

# 5. Create README files for each folder
readme_content <- list(
  "OBTAINED DATA" = "# Raw Data Files\n\nThis folder contains all original, unprocessed datasets:\n- House price data from UK Government\n- Broadband performance data from Ofcom\n- Crime data from Police databases\n- School data from Department for Education\n- Population data from ONS\n- Geographic mapping files\n\n**Note:** These files should not be modified. Keep originals for reproducibility.",
  
  "CLEANED DATA" = "# Processed Data Files\n\nThis folder contains cleaned and processed datasets:\n- Summary files by postcode\n- Combined datasets ready for analysis\n- Modeling datasets\n- Data quality reports\n\n**Generated by:** data cleaning scripts in CODE folder\n**Used for:** analysis and visualization",
  
  "CODE" = "# R Scripts and Programming Files\n\nMain analysis scripts:\n- `index.R` - Main analysis pipeline\n- `check_*.R` - Data validation scripts\n- `test_*.R` - Testing and debugging scripts\n\n**To run the complete analysis:**\n```r\nsource('CODE/index.R')\n```",
  
  "GRAPHS" = "# Visualization Outputs\n\nThis folder contains all generated graphs and charts:\n- House price visualizations\n- Broadband speed analysis\n- Crime rate charts\n- School performance graphs\n- Linear model plots\n- Correlation matrices\n\n**Generated by:** visualization sections in index.R",
  
  "RECOMMENDATION SYSTEM" = "# Area Recommendation Results\n\nThis folder contains the recommendation system outputs:\n- Ranked area recommendations\n- Scoring breakdowns\n- Top 3/10 recommendations\n- Algorithm documentation\n\n**Key files:**\n- `top_3_recommendations_with_addresses.csv` - Final results\n- Scoring methodology documentation",
  
  "REPORT" = "# Final Reports and Documentation\n\nThis folder will contain:\n- Executive summary\n- Technical methodology reports\n- Final presentation materials\n- Project documentation\n\n**Create files such as:**\n- Executive summary PDF\n- Technical report\n- Presentation slides"
)

for (folder in names(readme_content)) {
  readme_path <- file.path(folder, "README.md")
  writeLines(readme_content[[folder]], readme_path)
  cat("📝 Created README.md for", folder, "\n")
}

# 6. Create a master project summary
project_summary <- paste0(
  "# Area Recommendation Analysis Project\n\n",
  "**Objective:** Develop a multi-criteria recommendation system for residential areas in South & West Yorkshire\n\n",
  "## Key Features:\n",
  "- ✅ Multi-criteria scoring (House Prices 30%, Broadband 25%, Crime 25%, Schools 10%, Population 10%)\n",
  "- ✅ Data integration from 6+ government sources\n",
  "- ✅ MySQL database integration\n",
  "- ✅ Comprehensive statistical analysis\n",
  "- ✅ 20+ visualization outputs\n",
  "- ✅ Linear modeling and correlation analysis\n\n",
  "## Project Structure:\n",
  "```\n",
  "├── OBTAINED DATA/     # Raw datasets from government sources\n",
  "├── CLEANED DATA/      # Processed and cleaned datasets\n",
  "├── CODE/             # R scripts and analysis code\n",
  "├── GRAPHS/           # All visualization outputs\n",
  "├── RECOMMENDATION SYSTEM/  # Ranking results and scoring\n",
  "├── REPORT/           # Final documentation and reports\n",
  "└── PROJECT_ORGANIZATION_GUIDE.md  # This guide\n",
  "```\n\n",
  "## To Run Analysis:\n",
  "1. Ensure all raw data files are in OBTAINED DATA/\n",
  "2. Run: `source('CODE/index.R')`\n",
  "3. Check results in respective folders\n\n",
  "## Database Setup:\n",
  "- MySQL database with normalized tables\n",
  "- 3NF structure for optimal data storage\n",
  "- Automated data insertion from R scripts\n\n",
  "**Created:** ", Sys.Date(), "\n",
  "**Last Modified:** ", Sys.Date()
)

writeLines(project_summary, "PROJECT_SUMMARY.md")

cat("\n🎉 Project organization complete!\n")
cat("📊 Analysis project now properly structured\n")
cat("📁 All files categorized into appropriate folders\n")
cat("📝 README files created for each folder\n")
cat("🗂️ Master project guide and summary created\n\n")

cat("🚀 Next steps:\n")
cat("1. Review the PROJECT_ORGANIZATION_GUIDE.md for details\n")
cat("2. Place any missing raw data files in OBTAINED DATA/\n")
cat("3. Run the main analysis: source('CODE/index.R')\n")
cat("4. Check outputs in respective folders\n")
cat("5. Create final reports in REPORT/ folder\n")
